import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import {
  ArrowRight,
  BookOpen,
  Check,
  CheckCircle2,
  ChevronRight,
  Copy,
  Download,
  Eye,
  FileCheck,
  FileText,
  Filter,
  RefreshCw,
  Search,
  ShieldCheck,
  Zap,
} from "lucide-react";
import { toast } from "sonner";

import { PageHeader } from "@/components/page-header";
import { Button } from "@/components/ui/button";
import { TrustBadge } from "@/components/trust";
import { WorkflowStepper } from "@/components/workflow-stepper";
import { useLiveQuery } from "@/hooks/use-live-query";
import { supabase } from "@/integrations/supabase/client";
import { useI18n } from "@/context/language-context";
import { cn } from "@/lib/utils";

export const Route = createFileRoute("/_authenticated/outputs/")({
  head: () => ({
    meta: [
      { title: "Generated Outputs & Downloads — INTELLI-FORGE" },
      {
        name: "description",
        content:
          "Inspect, preview, verify, and download every audience artefact generated by INTELLI-FORGE.",
      },
      { property: "og:title", content: "Generated Outputs & Downloads — INTELLI-FORGE" },
      {
        property: "og:description",
        content: "View all generated artefacts, claim verifications, and download packages.",
      },
    ],
  }),
  component: OutputsPage,
});

function OutputsPage() {
  const { t } = useI18n();
  const [search, setSearch] = useState("");
  const [filterAudience, setFilterAudience] = useState<string>("all");
  const [copiedId, setCopiedId] = useState<string | null>(null);

  const { data: outputs, isLoading } = useLiveQuery(
    ["outputs_with_content"] as never,
    async () => {
      const { data } = await supabase
        .from("outputs")
        .select(
          "id, source_id, output_type, audience, tone, content, status, verification_status, evidence_coverage, created_at, updated_at",
        )
        .order("created_at", { ascending: false });
      return data ?? [];
    },
    ["outputs"],
  );

  const allOutputs = outputs ?? [];

  const audiences = Array.from(new Set(allOutputs.map((o) => o.audience).filter(Boolean)));

  const filtered = allOutputs.filter((item) => {
    const matchesSearch =
      search === "" ||
      item.output_type.toLowerCase().includes(search.toLowerCase()) ||
      item.audience.toLowerCase().includes(search.toLowerCase()) ||
      (item.content && item.content.toLowerCase().includes(search.toLowerCase()));

    const matchesAudience = filterAudience === "all" || item.audience === filterAudience;

    return matchesSearch && matchesAudience;
  });

  const handleDownload = (output: (typeof allOutputs)[0], format: "md" | "txt" | "json") => {
    let content = output.content || "";
    let mimeType = "text/plain";
    const extension = format;

    if (format === "md") {
      content = `# ${output.output_type}\n**Audience:** ${output.audience} | **Tone:** ${output.tone ?? "Standard"}\n**Coverage:** ${Math.round(output.evidence_coverage ?? 100)}%\n\n${output.content}`;
      mimeType = "text/markdown";
    } else if (format === "json") {
      content = JSON.stringify(output, null, 2);
      mimeType = "application/json";
    }

    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${output.output_type.toLowerCase().replace(/[^a-z0-9]/g, "-")}-${output.audience.toLowerCase().replace(/[^a-z0-9]/g, "-")}.${extension}`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`Downloaded ${format.toUpperCase()} file.`);
  };

  const handleCopy = (output: (typeof allOutputs)[0]) => {
    navigator.clipboard.writeText(output.content || "");
    setCopiedId(output.id);
    toast.success("Artefact content copied to clipboard.");
    setTimeout(() => setCopiedId(null), 2000);
  };

  const handleDownloadAll = () => {
    if (filtered.length === 0) return;
    const combined = filtered
      .map(
        (o) =>
          `# ${o.output_type}\nAudience: ${o.audience} | Tone: ${o.tone}\nStatus: ${o.status} | Grounding: ${Math.round(o.evidence_coverage ?? 100)}%\n\n${o.content}\n\n---\n`,
      )
      .join("\n\n");

    const blob = new Blob([combined], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `intelli-forge-all-outputs-${new Date().toISOString().slice(0, 10)}.md`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success(`Exported ${filtered.length} artefact(s) to Markdown bundle.`);
  };

  const firstOutput = allOutputs[0];

  return (
    <div>
      <WorkflowStepper
        currentStep="verify"
        sourceId={firstOutput?.source_id}
        outputId={firstOutput?.id}
      />

      <PageHeader
        eyebrow="Artefact Repository & Export Hub"
        title="Generated Outputs & Verification Library"
        description="Inspect claim traceability, preview rendered copy, and download ready-to-publish bundles across audiences."
        actions={
          <div className="flex flex-wrap items-center gap-2">
            {allOutputs.length > 0 && (
              <Button
                variant="outline"
                size="sm"
                onClick={handleDownloadAll}
                className="text-xs h-9 bg-white hover:bg-slate-50 border-slate-200"
              >
                <Download className="size-3.5 mr-1.5 text-slate-700" />
                Export All ({filtered.length}) as .MD
              </Button>
            )}

            {firstOutput && (
              <Link
                to="/outputs/$outputId"
                params={{ outputId: firstOutput.id }}
                className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-bold text-white shadow-md shadow-emerald-600/20 hover:bg-emerald-500 ring-2 ring-emerald-400/30 transition-all"
              >
                Step 4: Trace Latest Claims
                <ArrowRight className="size-3.5" />
              </Link>
            )}

            <Link
              to="/review"
              className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-4 py-2 text-xs font-bold text-white hover:bg-slate-800 transition-colors"
            >
              Review Queue (Step 5)
              <ChevronRight className="size-3.5" />
            </Link>
          </div>
        }
      />

      {/* Top Banner with Quick Actions */}
      {allOutputs.length > 0 && (
        <div className="mx-6 mt-6 rounded-2xl border-2 border-emerald-500/40 bg-emerald-50/90 p-5 flex flex-col md:flex-row items-center justify-between gap-4 shadow-sm animate-in fade-in">
          <div className="space-y-1 text-center md:text-left">
            <div className="flex items-center justify-center md:justify-start gap-2">
              <CheckCircle2 className="size-5 text-emerald-600" />
              <h3 className="text-sm font-bold text-slate-900">
                {allOutputs.length} Verified Artefacts Available
              </h3>
            </div>
            <p className="text-xs text-slate-600">
              Each artefact has sentence-level evidence mapping. Click any item to trace passages,
              download individual files, or advance to human approval.
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            {firstOutput && (
              <Link
                to="/outputs/$outputId"
                params={{ outputId: firstOutput.id }}
                className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-5 py-2.5 text-xs font-bold text-white shadow-md shadow-emerald-600/25 hover:bg-emerald-500 ring-2 ring-emerald-400/40 transition-all hover:scale-[1.02] active:scale-[0.98] whitespace-nowrap"
              >
                Next Step: Verify Claims (Step 4) <ArrowRight className="size-4" />
              </Link>
            )}
            <Link
              to="/review"
              className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-4 py-2.5 text-xs font-bold text-white hover:bg-slate-800 transition-colors whitespace-nowrap"
            >
              Human Review (Step 5) →
            </Link>
          </div>
        </div>
      )}

      {/* Search and Filters Bar */}
      <div className="mx-6 mt-6 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-border bg-white p-3 shadow-xs">
        <div className="flex flex-1 items-center gap-2 min-w-[240px]">
          <Search className="size-4 text-slate-400 shrink-0 ml-1" />
          <input
            type="text"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search by output type, audience, or keywords..."
            className="w-full bg-transparent text-xs text-foreground placeholder:text-muted-foreground focus:outline-none"
          />
        </div>

        {audiences.length > 0 && (
          <div className="flex items-center gap-1.5">
            <span className="text-xs text-muted-foreground font-medium flex items-center gap-1">
              <Filter className="size-3" /> Audience:
            </span>
            <select
              value={filterAudience}
              onChange={(e) => setFilterAudience(e.target.value)}
              className="rounded-lg border border-border bg-white px-2.5 py-1 text-xs text-foreground focus:outline-none"
            >
              <option value="all">All Audiences ({allOutputs.length})</option>
              {audiences.map((aud) => (
                <option key={aud} value={aud}>
                  {aud}
                </option>
              ))}
            </select>
          </div>
        )}
      </div>

      {/* Artefacts Grid / Cards */}
      <div className="p-6 space-y-4">
        {isLoading && (
          <div className="flex min-h-[300px] items-center justify-center">
            <RefreshCw className="size-6 text-emerald-600 animate-spin" />
          </div>
        )}

        {!isLoading && filtered.length === 0 && (
          <div className="rounded-2xl border border-dashed border-border bg-white p-12 text-center">
            <FileText className="size-10 text-muted-foreground/40 mx-auto" />
            <h3 className="mt-3 text-base font-bold text-foreground">No outputs found</h3>
            <p className="mt-1 text-xs text-muted-foreground max-w-sm mx-auto">
              {allOutputs.length === 0
                ? "You haven't generated any artefacts yet. Upload a source document in Step 1 to begin."
                : "No outputs matched your search query. Try clearing your search filter."}
            </p>
            {allOutputs.length === 0 && (
              <Link
                to="/upload"
                className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-bold text-white shadow-md hover:bg-emerald-500"
              >
                Go to Step 1: Upload Source Document →
              </Link>
            )}
          </div>
        )}

        {filtered.map((output) => {
          const wordCount = (output.content || "").split(/\s+/).filter(Boolean).length;
          return (
            <div
              key={output.id}
              className="group rounded-2xl border border-border bg-white p-6 shadow-xs hover:shadow-md transition-all flex flex-col justify-between"
            >
              {/* Header Info */}
              <div className="flex flex-wrap items-start justify-between gap-4">
                <div className="space-y-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <span className="inline-flex items-center gap-1 rounded-md bg-emerald-100 px-2 py-0.5 text-[11px] font-bold text-emerald-800">
                      Audience: {output.audience}
                    </span>
                    <span className="text-xs text-muted-foreground">
                      Tone: <strong className="text-foreground">{output.tone ?? "Standard"}</strong>
                    </span>
                    <span className="text-xs text-muted-foreground">· {wordCount} words</span>
                  </div>

                  <h3 className="text-base font-bold text-foreground pt-1">{output.output_type}</h3>
                </div>

                <div className="flex items-center gap-3">
                  <span className="font-mono text-xs font-semibold text-emerald-700 bg-emerald-50 border border-emerald-200 px-2.5 py-1 rounded-lg">
                    {output.evidence_coverage != null
                      ? `${Math.round(output.evidence_coverage)}% Traced`
                      : "Evidence Traced"}
                  </span>
                  <TrustBadge state={output.verification_status} />
                </div>
              </div>

              {/* Text Preview Snippet */}
              <div className="my-4 rounded-xl bg-slate-50 p-4 border border-slate-100 text-xs text-slate-700 leading-relaxed font-sans line-clamp-3">
                {output.content}
              </div>

              {/* Action Toolbar */}
              <div className="pt-3 border-t border-slate-100 flex flex-wrap items-center justify-between gap-3">
                {/* Download Options */}
                <div className="flex flex-wrap items-center gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleDownload(output, "md")}
                    className="h-8 text-xs bg-white hover:bg-slate-50 border-slate-200"
                  >
                    <Download className="size-3 mr-1 text-slate-600" />
                    Download .md
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleDownload(output, "txt")}
                    className="h-8 text-xs bg-white hover:bg-slate-50 border-slate-200"
                  >
                    <Download className="size-3 mr-1 text-slate-600" />
                    .txt
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleDownload(output, "json")}
                    className="h-8 text-xs bg-white hover:bg-slate-50 border-slate-200"
                  >
                    .json
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => handleCopy(output)}
                    className="h-8 text-xs bg-white hover:bg-slate-50 border-slate-200"
                  >
                    {copiedId === output.id ? (
                      <Check className="size-3 text-emerald-600 mr-1" />
                    ) : (
                      <Copy className="size-3 mr-1 text-slate-600" />
                    )}
                    {copiedId === output.id ? "Copied" : "Copy"}
                  </Button>
                </div>

                {/* Primary Navigation to Next Steps */}
                <div className="flex items-center gap-2">
                  <Link
                    to="/outputs/$outputId"
                    params={{ outputId: output.id }}
                    className="inline-flex items-center gap-1.5 rounded-xl bg-emerald-600 px-4 py-2 text-xs font-bold text-white shadow-sm hover:bg-emerald-500 ring-2 ring-emerald-400/30 transition-all hover:scale-[1.01] active:scale-[0.99]"
                  >
                    Step 4: Trace Evidence <ArrowRight className="size-3.5" />
                  </Link>

                  {output.status === "approved" ? (
                    <Link
                      to="/distribution"
                      className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-3.5 py-2 text-xs font-bold text-white hover:bg-slate-800 transition-colors"
                    >
                      Distribute (Step 6) →
                    </Link>
                  ) : (
                    <Link
                      to="/review"
                      search={{ outputId: output.id }}
                      className="inline-flex items-center gap-1.5 rounded-xl bg-slate-100 hover:bg-slate-200 px-3.5 py-2 text-xs font-bold text-slate-800 transition-colors"
                    >
                      Review (Step 5)
                    </Link>
                  )}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
